interface CurrentWeather {
  is_day: number
  temperature: number
  time: string
  weathercode: number
  winddirection: number
  windspeed: number
}

interface Daily {
  apparent_temperature_max_best_match: [number]
  apparent_temperature_max_gfs_global: [number]
  apparent_temperature_max_icon_seamless: [number]
  apparent_temperature_max_meteofrance_arome_france_hd: [number]
  apparent_temperature_min_best_match: [number]
  apparent_temperature_min_gfs_global: [number]
  apparent_temperature_min_icon_seamless: [number]
  apparent_temperature_min_meteofrance_arome_france_hd: [number]
  precipitation_hours_best_match: [number]
  precipitation_hours_ecmwf_ifs04: [number]
  precipitation_hours_gfs_global: [number]
  precipitation_hours_icon_seamless: [number]
  precipitation_hours_meteofrance_arome_france_hd: [number]
  precipitation_probability_max_best_match: [number]
  precipitation_probability_max_gfs_global: [number]
  precipitation_sum_best_match: [number]
  precipitation_sum_ecmwf_ifs04: [number]
  precipitation_sum_gfs_global: [number]
  precipitation_sum_icon_seamless: [number]
  precipitation_sum_meteofrance_arome_france_hd: [string]
  rain_sum_best_match: [number]
  rain_sum_gfs_global: [number]
  rain_sum_icon_seamless: [number]
  shortwave_radiation_sum_best_match: [number]
  shortwave_radiation_sum_gfs_global: [number]
  shortwave_radiation_sum_icon_seamless: [number]
  shortwave_radiation_sum_meteofrance_arome_france_hd: [JSON]
  showers_sum_best_match: [number]
  showers_sum_gfs_global: [number]
  showers_sum_icon_seamless: [number]
  sunrise: [string]
  sunset: [string]
  temperature_2m_max_best_match: [number]
  temperature_2m_max_ecmwf_ifs04: [number]
  temperature_2m_max_gfs_global: [number]
  temperature_2m_max_icon_seamless: [number]
  temperature_2m_max_meteofrance_arome_france_hd: [number]
  temperature_2m_min_best_match: [number]
  temperature_2m_min_ecmwf_ifs04: [number]
  temperature_2m_min_gfs_global: [number]
  temperature_2m_min_icon_seamless: [number]
  temperature_2m_min_meteofrance_arome_france_hd: [number]
  time: [string]
  uv_index_clear_sky_max_best_match: [number]
  uv_index_clear_sky_max_gfs_global: [number]
  uv_index_max_best_match: [number]
  uv_index_max_gfs_global: [number]
  winddirection_10m_dominant_best_match: [number]
  winddirection_10m_dominant_ecmwf_ifs04: [number]
  winddirection_10m_dominant_gfs_global: [number]
  winddirection_10m_dominant_icon_seamless: [number]
  winddirection_10m_dominant_meteofrance_arome_france_hd: [number]
}
interface DailyUnits {
  apparent_temperature_max_best_match: string
  apparent_temperature_max_gfs_global: string
  apparent_temperature_max_icon_seamless: string
  apparent_temperature_max_meteofrance_arome_france_hd: string
  apparent_temperature_min_best_match: string
  apparent_temperature_min_gfs_global: string
  apparent_temperature_min_icon_seamless: string
  apparent_temperature_min_meteofrance_arome_france_hd: string
  precipitation_hours_best_match: string
  precipitation_hours_ecmwf_ifs04: string
  precipitation_hours_gfs_global: string
  precipitation_hours_icon_seamless: string
  precipitation_hours_meteofrance_arome_france_hd: string
  precipitation_probability_max_best_match: string
  precipitation_probability_max_gfs_global: string
  precipitation_sum_best_match: string
  precipitation_sum_ecmwf_ifs04: string
  precipitation_sum_gfs_global: string
  precipitation_sum_icon_seamless: string
  precipitation_sum_meteofrance_arome_france_hd: string
  rain_sum_best_match: string
  rain_sum_gfs_global: string
  rain_sum_icon_seamless: string
  shortwave_radiation_sum_best_match: string
  shortwave_radiation_sum_gfs_global: string
  shortwave_radiation_sum_icon_seamless: string
  shortwave_radiation_sum_meteofrance_arome_france_hd: string
  showers_sum_best_match: string
  showers_sum_gfs_global: string
  showers_sum_icon_seamless: string
  sunrise: string
  sunset: string
  temperature_2m_max_best_match: string
  temperature_2m_max_ecmwf_ifs04: string
  temperature_2m_max_gfs_global: string
  temperature_2m_max_icon_seamless: string
  temperature_2m_max_meteofrance_arome_france_hd: string
  temperature_2m_min_best_match: string
  temperature_2m_min_ecmwf_ifs04: string
  temperature_2m_min_gfs_global: string
  temperature_2m_min_icon_seamless: string
  temperature_2m_min_meteofrance_arome_france_hd: string
  time: string
  uv_index_clear_sky_max_best_match: string
  uv_index_clear_sky_max_gfs_global: string
  uv_index_max_best_match: string
  uv_index_max_gfs_global: string
  winddirection_10m_dominant_best_match: string
  winddirection_10m_dominant_ecmwf_ifs04: string
  winddirection_10m_dominant_gfs_global: string
  winddirection_10m_dominant_icon_seamless: string
  winddirection_10m_dominant_meteofrance_arome_france_hd: string
}
interface Hourly {
  apparent_temperature_best_match: [number]
  apparent_temperature_gfs_global: [number]
  apparent_temperature_icon_seamless: [number]
  apparent_temperature_meteofrance_arome_france_hd: [number]
  cloudcover_best_match: [number]
  cloudcover_ecmwf_ifs04: [number]
  cloudcover_gfs_global: [number]
  cloudcover_icon_seamless: [number]
  cloudcover_meteofrance_arome_france_hd: [string]
  freezinglevel_height_best_match: [number]
  freezinglevel_height_gfs_global: [number]
  freezinglevel_height_icon_seamless: [number]
  is_day_best_match: [number]
  is_day_ecmwf_ifs04: [number]
  is_day_gfs_global: [number]
  is_day_icon_seamless: [number]
  is_day_meteofrance_arome_france_hd: [number]
  relativehumidity_2m_best_match: [number]
  relativehumidity_2m_gfs_global: [number]
  relativehumidity_2m_icon_seamless: [number]
  relativehumidity_2m_meteofrance_arome_france_hd: [number]
  soil_moisture_27_81cm_best_match: [number]
  soil_moisture_27_81cm_icon_seamless: [number]
  soil_moisture_3_9cm_best_match: [number]
  soil_moisture_3_9cm_icon_seamless: [number]
  soil_temperature_54cm_best_match: [number]
  soil_temperature_54cm_icon_seamless: [number]
  soil_temperature_6cm_best_match: [number]
  soil_temperature_6cm_icon_seamless: [number]
  temperature_2m_best_match: [number]
  temperature_2m_ecmwf_ifs04: [number]
  temperature_2m_gfs_global: [number]
  temperature_2m_icon_seamless: [number]
  temperature_2m_meteofrance_arome_france_hd: [number]
  time: [string]
  vapor_pressure_deficit_best_match: [number]
  vapor_pressure_deficit_gfs_global: [number]
  vapor_pressure_deficit_icon_seamless: [number]
  vapor_pressure_deficit_meteofrance_arome_france_hd: [number]
}
interface HourlyUnits {
  apparent_temperature_best_match: string
  apparent_temperature_gfs_global: string
  apparent_temperature_icon_seamless: string
  apparent_temperature_meteofrance_arome_france_hd: string
  cloudcover_best_match: string
  cloudcover_ecmwf_ifs04: string
  cloudcover_gfs_global: string
  cloudcover_icon_seamless: string
  cloudcover_meteofrance_arome_france_hd: string
  freezinglevel_height_best_match: string
  freezinglevel_height_gfs_global: string
  freezinglevel_height_icon_seamless: string
  is_day_best_match: string
  is_day_ecmwf_ifs04: string
  is_day_gfs_global: string
  is_day_icon_seamless: string
  is_day_meteofrance_arome_france_hd: string
  relativehumidity_2m_best_match: string
  relativehumidity_2m_gfs_global: string
  relativehumidity_2m_icon_seamless: string
  relativehumidity_2m_meteofrance_arome_france_hd: string
  soil_moisture_27_81cm_best_match: string
  soil_moisture_27_81cm_icon_seamless: string
  soil_moisture_3_9cm_best_match: string
  soil_moisture_3_9cm_icon_seamless: string
  soil_temperature_54cm_best_match: string
  soil_temperature_54cm_icon_seamless: string
  soil_temperature_6cm_best_match: string
  soil_temperature_6cm_icon_seamless: string
  temperature_2m_best_match: string
  temperature_2m_ecmwf_ifs04: string
  temperature_2m_gfs_global: string
  temperature_2m_icon_seamless: string
  temperature_2m_meteofrance_arome_france_hd: string
  time: string
  vapor_pressure_deficit_best_match: string
  vapor_pressure_deficit_gfs_global: string
  vapor_pressure_deficit_icon_seamless: string
  vapor_pressure_deficit_meteofrance_arome_france_hd: string
}

interface Root {
  current_weather: CurrentWeather
  daily: Daily
  daily_units: DailyUnits
  elevation: number
  generationtime_ms: number
  hourly: Hourly
  hourly_units: HourlyUnits
  latitude: number
  longitude: number
  timezone: string
  timezone_abbreviation: string
  utc_offset_seconds: number
}